name: Deploy on gh-pages

on:
  repository_dispatch:
    types: [trigger-download]

jobs:
  download-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download from Dndkit repo
        uses: actions/download-artifact@v4
        with:
          path: ./dndkit
      - name: Commit and Push
        run: |
          git config --global user.email "38601700+dominus10@users.noreply.github.com"
          git config --global user.name "gh-pages action bot"
          ls
          git add ./dndkit
          git commit -m "Deploy $REPO_NAME build"
          git subtree push --prefix ./dndkit origin gh-pages

  deploy:
    runs-on: ubuntu-latest
    name: Deploy to GH-Pages
    needs: download-build
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_dir: dndkit
