name: Deploy on gh-pages

on:
  repository_dispatch:
    types: [trigger-download]

jobs:
  download-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download from Dndkit repo
        uses: actions/download-artifact@v4
        with:
          path: ./temp-build

      - name: Move to temp subdir
        run: |
          REPO_NAME="${{ github.event.client_payload.repository }}"
          mkdir -p "./$REPO_NAME"
          mv ./temp-build/* "./$REPO_NAME/"

      - name: Commit and Push
        run: |
          git add .
          git commit -m "Deploy $REPO_NAME build"
          git push

  deploy:
    runs-on: ubuntu-latest
    name: Deploy to GH-Pages
    needs: download-build
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_dir: dndkit
