name: Deploy on gh-pages

on:
  repository_dispatch:
    types: [trigger-download]

jobs:
  download-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download from Dndkit repo
        uses: actions/download-artifact@v4

  deploy:
    runs-on: ubuntu-latest
    name: Deploy to GH-Pages
    needs: download-build
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Unpack
        run: |
          ls ./build
          mkdir -p ./dndkit
          cp -R ./build/* ./dndkit/
          git config --global user.email "38601700+dominus10@users.noreply.github.com"
          git config --global user.name "gh-pages action bot"
          git add ./dndkit
          git commit -m "Deploy build to dndkit"
          git subtree push --prefix dndkit origin gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_dir: dndkit
          enable_jekyll: true
